apiVersion: v1
kind: Pod
metadata:
  name: test-pod-configmap
  labels:
    name: test
    environment: sandbox
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    envFrom:
      - configMapRef:
          name: test-configmap
