apiVersion: v1
kind: Pod
metadata:
  name: test-pod-secret
  labels:
    name: test
    environment: sandbox
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: test-secret
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
